version: 2

jobs:
  test:
    docker:
      - image: mhart/alpine-node:8.4.0
    steps:
      - checkout
      - run: echo 'export PATH=${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin' >> $BASH_ENV
      - run: yarn install
      - run: yarn lint
      - run: yarn test

workflows:
  version: 2
  test_components:
    jobs:
        - test
